-- +--------------------------------------------------------------------+
-- | Copyright CiviCRM LLC. All rights reserved.                        |
-- |                                                                    |
-- | This work is published under the GNU AGPLv3 license with some      |
-- | permitted exceptions and without any warranty. For full license    |
-- | and copyright information, see https://civicrm.org/licensing       |
-- +--------------------------------------------------------------------+
--
-- Generated from schema.tpl
-- DO NOT EDIT.  Generated by CRM_Core_CodeGen
--
-- /*******************************************************
-- *
-- * Clean up the existing tables - this section generated from drop.tpl
-- *
-- *******************************************************/

SET FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS `civicrm_event_calendar_event_type`;
DROP TABLE IF EXISTS `civicrm_event_calendar_participant`;
DROP TABLE IF EXISTS `civicrm_event_calendar`;

SET FOREIGN_KEY_CHECKS=1;
-- /*******************************************************
-- *
-- * Create new tables
-- *
-- *******************************************************/

-- /*******************************************************
-- *
-- * civicrm_event_calendar
-- *
-- * Stores Event Calendar parameters for display
-- *
-- *******************************************************/
CREATE TABLE `civicrm_event_calendar` (
  `id` int unsigned NOT NULL AUTO_INCREMENT COMMENT 'Unique EventCalendar ID',
  `calendar_title` varchar(255) COMMENT 'Calendar Title',
  `calendar_type` varchar(64) COMMENT 'Null or resource name',
  `show_past_events` tinyint COMMENT 'Show Past Events',
  `show_end_date` tinyint COMMENT 'Show End Date',
  `show_public_events` tinyint COMMENT 'Show Only Public or All',
  `events_by_month` tinyint COMMENT 'Use the Month param in the calendar',
  `event_timings` tinyint COMMENT 'Show the event timing',
  `events_from_month` int unsigned COMMENT 'How many months to show events',
  `event_type_filters` tinyint COMMENT 'Whether to show event type filters',
  `week_begins_from_day` tinyint COMMENT 'Show week begins on',
  `time_format_24_hour` tinyint COMMENT 'Use 24 hour format',
  `recurring_event` tinyint COMMENT 'Show recurring events',
  `enrollment_status` tinyint COMMENT 'Show enrollment status',
  PRIMARY KEY (`id`)
)
ENGINE=InnoDB;

-- /*******************************************************
-- *
-- * civicrm_event_calendar_participant
-- *
-- * Resources and colors
-- *
-- *******************************************************/
CREATE TABLE `civicrm_event_calendar_participant` (
  `id` int unsigned NOT NULL AUTO_INCREMENT COMMENT 'Unique EventCalendarParticipant ID',
  `event_calendar_id` int unsigned COMMENT 'FK to Event Calendar',
  `contact_id` int unsigned COMMENT 'FK to Contact',
  `event_color` varchar(255) COMMENT 'Hex code for event type display color',
  PRIMARY KEY (`id`),
  CONSTRAINT FK_civicrm_event_calendar_participant_event_calendar_id FOREIGN KEY (`event_calendar_id`) REFERENCES `civicrm_event_calendar`(`id`) ON DELETE CASCADE,
  CONSTRAINT FK_civicrm_event_calendar_participant_contact_id FOREIGN KEY (`contact_id`) REFERENCES `civicrm_contact`(`id`) ON DELETE CASCADE
)
ENGINE=InnoDB;

-- /*******************************************************
-- *
-- * civicrm_event_calendar_event_type
-- *
-- * Event types and colors, FK to Event Calendar ID
-- *
-- *******************************************************/
CREATE TABLE `civicrm_event_calendar_event_type` (
  `id` int unsigned NOT NULL AUTO_INCREMENT COMMENT 'Unique EventCalendarEventType ID',
  `event_calendar_id` int unsigned COMMENT 'FK to Event Calendar',
  `event_type` int unsigned COMMENT 'Event Type id',
  `event_color` varchar(255) COMMENT 'Hex code for event type display color',
  PRIMARY KEY (`id`),
  CONSTRAINT FK_civicrm_event_calendar_event_type_event_calendar_id FOREIGN KEY (`event_calendar_id`) REFERENCES `civicrm_event_calendar`(`id`) ON DELETE CASCADE
)
ENGINE=InnoDB;
